### PR TITLE
Update working draft revision to N4971

### PR DESCRIPTION
**Pull request by Tu-Code**
Fixes #4278

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Perhaps the PR should be opened at https://github.com/microsoft/STL/pulls.

**Comment by Tu-Code** [comment]
Thank you!

You mean I should create my own branch based off the main branch? Instead
of forking the repository first?

Are there any naming conventions I should follow, please?

**Comment by frederick-vs-ja** [comment]
> You mean I should create my own branch based off the main branch? Instead of forking the repository first? Are there any naming conventions I should follow, please?

It's recommended but not strictly required to use a branch other than `main`, because the `main` branch should be used to follow the upstream, and the commits will be a mess if you create two PRs from the same branch.

Currently there's no naming conventions.

**Comment by Tu-Code** [comment]
@frederick-vs-ja , thank you.

I tried opening the PR on the https://github.com/microsoft/STL/pulls page but I do not have permission to microsoft/STL.git hence me creating my own fork.

Is this what you meant, please?

**Comment by frederick-vs-ja** [comment]
I think you can update your branch again (e.g. by reset and force-push) and then Github will automatically allow you to create a PR there.

**Pull request closed without merging**
